"""gmshjax: AD mesh creation for JAX."""

from .ad.compiled import build_quality_value_and_grad
from .ad.mode1 import (
    Mode1BenchmarkResult,
    Mode1OptimizationResult,
    Mode1StepDiagnostics,
    benchmark_mode1_fixed_topology,
    export_mode1_artifacts,
    optimize_mode1_fixed_topology,
    summarize_mode1_result,
)
from .ad.workflow import Mode1Domain, Mode1WorkflowRun, initialize_mode1_domain, run_mode1_workflow
from .ad.pipeline import (
    build_model_parametric_quality_value_and_grad,
    build_parametric_quality_value_and_grad,
    default_param_vector,
    default_params,
)
from .ad.modes import MeshMovementMode, MeshMovementModeSpec, get_mesh_movement_mode, get_mesh_movement_modes
from .ad.restart import (
    RestartPhase,
    RestartQuadOptimizationResult,
    RestartTetOptimizationResult,
    RestartTriOptimizationResult,
    optimize_points_fixed_topology,
    optimize_remesh_restart_quad,
    optimize_remesh_restart_tet,
    optimize_remesh_restart_tri,
    quad_topology_from_elements,
    tet_topology_from_elements,
    triangle_topology_from_elements,
)
from .ad.straight_through import straight_through_quad_connectivity_energy, straight_through_quad_diagonal_weights
from .ad.surrogate import quad_split_candidate_qualities, soft_quad_connectivity_energy, soft_quad_diagonal_weights
from .io.exports import GmshElementBlock, export_gmsh_msh, export_metrics_json, export_snapshot_npz, load_snapshot_npz
from .io.gmsh_viewer import launch_gmsh_viewer
from .io.imports import ImportedGmshMesh, load_gmsh_msh
from .mesh.adaptive import AdaptiveHistory, adaptive_remesh_tri
from .mesh.adaptive_quad import QuadAdaptiveHistory, adaptive_remesh_quad, quad_area_magnitudes, quad_refinement_priority
from .mesh.adaptive_tet import TetAdaptiveHistory, adaptive_remesh_tet, tet_refinement_priority, tet_volume_magnitudes
from .mesh.boundary import (
    BoundaryCurves2D,
    BoundaryCurves3D,
    boundary_constrained_points,
    cleanup_uv_tri_mesh,
    evaluate_surface_patch,
    line_segment,
    sinusoidal_top_boundary,
    smooth_boundary_constrained_points,
    smooth_surface_boundary_constrained_points,
    surface_boundary_constrained_points,
    surface_front_tri_mesh,
    surface_parametric_point_cloud,
    surface_point_cloud,
    surface_transfinite_interpolation,
    transfinite_interpolation,
    uv_triangle_quality_objective,
)
from .mesh.connectivity_opt import evaluate_edge_flip_candidates, evaluate_laplacian_smoothing_candidates
from .mesh.factory import make_unit_square_model
from .mesh.generators import project_cube_points_to_sphere, unit_square_points
from .mesh.manifold import DeformationParams, apply_deformation
from .mesh.mutation import (
    TriMeshBuffer,
    active_elements,
    active_points,
    collapse_triangle,
    flip_diagonal,
    make_tri_mesh_buffer,
    split_triangle,
)
from .mesh.mutation_qt import (
    QuadMeshBuffer,
    TetMeshBuffer,
    active_quad_elements,
    active_quad_points,
    active_tet_elements,
    active_tet_points,
    collapse_quad,
    collapse_tet,
    make_quad_mesh_buffer,
    make_tet_mesh_buffer,
    split_quad,
    split_tet,
)
from .mesh.diagnostics import line_diagnostics, quad_diagnostics, tet_diagnostics, tri_diagnostics
from .mesh.domains import (
    DomainMeshMetadata,
    box_volume_tet_mesh,
    box_volume_tet_mesh_tagged,
    extruded_polygon_tet_mesh,
    implicit_volume_tet_mesh,
    implicit_volume_tet_mesh_tagged,
    polygon_domain_quad_mesh,
    polygon_domain_quad_mesh_tagged,
    polygon_domain_tri_mesh,
    polygon_domain_tri_mesh_tagged,
)
from .mesh.operators import (
    edge_lengths,
    graph_laplacian_step,
    line_element_lengths,
    line_mesh_quality_energy,
    quad_mesh_quality_energy,
    quad_icn,
    quad_ige,
    tet_mesh_quality_energy,
    tet_icn,
    tet_ige,
    triangle_icn,
    triangle_ige,
    triangle_signed_areas,
)
from .mesh.refine import (
    batched_refinement_step,
    refinement_midpoints,
    select_refinement_candidates,
    triangle_area_magnitudes,
    triangle_refinement_priority,
)
from .mesh.topology import MeshTopology, mesh_topology_from_points_and_elements, polyline_mesh, unit_cube_tet_mesh, unit_interval_line_mesh, unit_square_quad_mesh, unit_square_tri_mesh
from .model import GEntity, MeshModel, MeshState, update_points
from .numpy_impl import NumpyDeformationParams, NumpyMeshTopology
from .runtime import get_runtime_precision, jax_float_dtype, numpy_float_dtype, set_runtime_precision
from .visualization import build_mode1_viper_payload, build_pyvista_dataset, plot_mode1_matplotlib, plot_mode1_pyvista, plot_mode1_viper

__all__ = [
    "AdaptiveHistory",
    "BoundaryCurves2D",
    "BoundaryCurves3D",
    "DeformationParams",
    "DomainMeshMetadata",
    "GEntity",
    "GmshElementBlock",
    "ImportedGmshMesh",
    "MeshModel",
    "MeshState",
    "MeshTopology",
    "NumpyDeformationParams",
    "NumpyMeshTopology",
    "QuadAdaptiveHistory",
    "QuadMeshBuffer",
    "TetMeshBuffer",
    "TetAdaptiveHistory",
    "TriMeshBuffer",
    "active_elements",
    "active_points",
    "active_quad_elements",
    "active_quad_points",
    "active_tet_elements",
    "active_tet_points",
    "adaptive_remesh_quad",
    "adaptive_remesh_tet",
    "adaptive_remesh_tri",
    "apply_deformation",
    "batched_refinement_step",
    "boundary_constrained_points",
    "benchmark_mode1_fixed_topology",
    "build_mode1_viper_payload",
    "build_model_parametric_quality_value_and_grad",
    "build_parametric_quality_value_and_grad",
    "build_pyvista_dataset",
    "build_quality_value_and_grad",
    "box_volume_tet_mesh",
    "box_volume_tet_mesh_tagged",
    "MeshMovementMode",
    "MeshMovementModeSpec",
    "Mode1BenchmarkResult",
    "Mode1Domain",
    "Mode1OptimizationResult",
    "Mode1StepDiagnostics",
    "Mode1WorkflowRun",
    "RestartPhase",
    "RestartQuadOptimizationResult",
    "RestartTetOptimizationResult",
    "RestartTriOptimizationResult",
    "cleanup_uv_tri_mesh",
    "collapse_quad",
    "collapse_tet",
    "collapse_triangle",
    "default_param_vector",
    "default_params",
    "edge_lengths",
    "evaluate_edge_flip_candidates",
    "evaluate_laplacian_smoothing_candidates",
    "evaluate_surface_patch",
    "extruded_polygon_tet_mesh",
    "export_gmsh_msh",
    "export_mode1_artifacts",
    "export_metrics_json",
    "export_snapshot_npz",
    "flip_diagonal",
    "graph_laplacian_step",
    "get_mesh_movement_mode",
    "get_mesh_movement_modes",
    "initialize_mode1_domain",
    "line_diagnostics",
    "line_element_lengths",
    "line_segment",
    "line_mesh_quality_energy",
    "launch_gmsh_viewer",
    "load_gmsh_msh",
    "make_quad_mesh_buffer",
    "make_tet_mesh_buffer",
    "make_tri_mesh_buffer",
    "make_unit_square_model",
    "load_snapshot_npz",
    "mesh_topology_from_points_and_elements",
    "optimize_mode1_fixed_topology",
    "quad_area_magnitudes",
    "quad_icn",
    "quad_ige",
    "quad_refinement_priority",
    "quad_diagnostics",
    "refinement_midpoints",
    "project_cube_points_to_sphere",
    "optimize_points_fixed_topology",
    "optimize_remesh_restart_quad",
    "optimize_remesh_restart_tet",
    "optimize_remesh_restart_tri",
    "quad_mesh_quality_energy",
    "quad_split_candidate_qualities",
    "quad_topology_from_elements",
    "plot_mode1_matplotlib",
    "plot_mode1_pyvista",
    "plot_mode1_viper",
    "polygon_domain_quad_mesh",
    "polygon_domain_quad_mesh_tagged",
    "polygon_domain_tri_mesh",
    "polygon_domain_tri_mesh_tagged",
    "polyline_mesh",
    "select_refinement_candidates",
    "set_runtime_precision",
    "get_runtime_precision",
    "jax_float_dtype",
    "numpy_float_dtype",
    "run_mode1_workflow",
    "sinusoidal_top_boundary",
    "smooth_boundary_constrained_points",
    "smooth_surface_boundary_constrained_points",
    "split_quad",
    "split_tet",
    "split_triangle",
    "soft_quad_connectivity_energy",
    "soft_quad_diagonal_weights",
    "straight_through_quad_connectivity_energy",
    "straight_through_quad_diagonal_weights",
    "surface_boundary_constrained_points",
    "surface_front_tri_mesh",
    "surface_parametric_point_cloud",
    "surface_point_cloud",
    "surface_transfinite_interpolation",
    "summarize_mode1_result",
    "tet_icn",
    "tet_ige",
    "tet_mesh_quality_energy",
    "tet_diagnostics",
    "implicit_volume_tet_mesh",
    "implicit_volume_tet_mesh_tagged",
    "tet_refinement_priority",
    "tet_topology_from_elements",
    "tet_volume_magnitudes",
    "transfinite_interpolation",
    "triangle_area_magnitudes",
    "triangle_icn",
    "triangle_ige",
    "triangle_refinement_priority",
    "triangle_signed_areas",
    "triangle_topology_from_elements",
    "tri_diagnostics",
    "unit_cube_tet_mesh",
    "unit_interval_line_mesh",
    "unit_square_points",
    "unit_square_quad_mesh",
    "unit_square_tri_mesh",
    "update_points",
    "uv_triangle_quality_objective",
]
